from src.soup.soup.components.camera import *
from src.soup.soup.components.circle import *
from src.soup.soup.components.ear import *
from src.soup.soup.components.eatable import *
from src.soup.soup.components.eye import *
from src.soup.soup.components.friction import *
from src.soup.soup.components.mouth import *
from src.soup.soup.components.movement import *
from src.soup.soup.components.velocity import *
from src.soup.soup.components.brain import *
from src.soup.soup.components.rigid_body import *
from src.soup.soup.components.speaker import *
