from src.soup.soup.system.controller_system import *
from src.soup.soup.system.eye_system import *
from src.soup.soup.system.food_system import *
from src.soup.soup.system.friction_system import *
from src.soup.soup.system.mouth_system import *
from src.soup.soup.system.movement_system import *
from src.soup.soup.system.render import *
from src.soup.soup.system.velocity_system import *
from src.soup.soup.system.brain_system import *
from src.soup.soup.system.sound_system import *
